import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Layers, Plus, Search, CheckCircle2, XCircle,
  Building2, Edit2, ToggleLeft, ToggleRight
} from 'lucide-react';
import { Button } from '@/shared/components/ui/Button';
import { Input } from '@/shared/components/ui/Input';
import { ClearableInput } from '@/shared/components/ui/ClearableInput';
import { Card, CardContent } from '@/shared/components/ui/Card';
import { Segment } from '@/modules/employees/domain/entities/Segment';
import { SupabaseSegmentRepository } from '../../infrastructure/repositories/SupabaseSegmentRepository';
import { useAuthenticatedIdentity } from '@/modules/auth/presentation/hooks/useAuthenticatedIdentity';

// ─── Modal de Segmento ────────────────────────────────────────────────────────
function SegmentModal({
  seg, organizationId, onClose, onSave,
}: {
  seg?: Segment;
  organizationId: string;
  onClose: () => void;
  onSave: (s: Segment) => void;
}) {
  const [nome, setNome] = useState(seg?.nome || '');
  const [descricao, setDescricao] = useState(seg?.descricao || '');

  const handleSave = () => {
    if (!nome.trim()) return;
    
    if (seg) {
      onSave({
        ...seg,
        nome: nome.trim(),
        descricao: descricao.trim(),
      });
    } else {
      onSave({
        id: '', // Will be generated by DB
        organization_id: organizationId,
        nome: nome.trim(),
        descricao: descricao.trim(),
        status: 'ativo',
        created_at: '',
        updated_at: '',
      });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full animate-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between px-6 pt-6 pb-4 border-b border-slate-100">
          <h3 className="text-base font-extrabold text-slate-900">
            {seg ? 'Editar Segmento' : 'Novo Segmento'}
          </h3>
          <button onClick={onClose} className="p-1.5 hover:bg-slate-100 rounded-full">
            <XCircle className="h-4 w-4 text-slate-400" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-4">
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Nome *</label>
            <Input
              value={nome}
              onChange={e => setNome(e.target.value)}
              placeholder="Ex: Agroindústria, Mineração, Logística..."
              className="h-9 text-sm"
            />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Descrição</label>
            <textarea
              value={descricao}
              onChange={e => setDescricao(e.target.value)}
              placeholder="Descreva o segmento de atuação das empresas."
              rows={3}
              className="w-full px-3 py-2 rounded-lg border border-slate-300 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-none"
            />
          </div>

          <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-3">
            <p className="text-[10px] font-bold text-indigo-700 flex items-center gap-1.5">
              <Layers className="h-3 w-3" />
              Segmentos representam a área de atuação das empresas cadastradas na plataforma Hub.IA.
            </p>
          </div>
        </div>

        <div className="flex gap-3 justify-end px-6 pb-6">
          <Button variant="outline" onClick={onClose} className="h-9 text-xs">Cancelar</Button>
          <Button
            onClick={handleSave}
            disabled={!nome.trim()}
            className="bg-indigo-600 hover:bg-indigo-700 text-white h-9 text-xs font-bold flex items-center gap-2"
          >
            <CheckCircle2 className="h-3.5 w-3.5" /> {seg ? 'Salvar' : 'Criar Segmento'}
          </Button>
        </div>
      </div>
    </div>
  );
}

// ─── SegmentsPage ─────────────────────────────────────────────────────────────
export default function SegmentsPage() {
  const queryClient = useQueryClient();
  const { data: identity } = useAuthenticatedIdentity();
  const orgId = identity?.organizationId || '';
  const repo = new SupabaseSegmentRepository();

  const { data: segments = [] } = useQuery({
    queryKey: ['segments', orgId],
    queryFn: () => repo.listSegments(orgId),
    enabled: Boolean(orgId),
  });

  const saveMutation = useMutation({
    mutationFn: async (s: Segment) => {
      if (s.id) {
        return repo.updateSegment(s.id, { nome: s.nome, descricao: s.descricao, status: s.status });
      } else {
        return repo.createSegment({
          organization_id: s.organization_id,
          nome: s.nome,
          descricao: s.descricao,
          status: s.status,
        });
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['segments', orgId] });
      setModal({ open: false });
    }
  });

  const toggleStatusMutation = useMutation({
    mutationFn: async (id: string) => {
      const seg = segments.find(x => x.id === id);
      if (!seg) throw new Error('Segmento não encontrado');
      return repo.updateSegment(id, { status: seg.status === 'ativo' ? 'inativo' : 'ativo' });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['segments', orgId] });
    }
  });

  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState<'Todos' | 'Ativos' | 'Inativos'>('Todos');
  const [modal, setModal] = useState<{ open: boolean; seg?: Segment }>({ open: false });

  const filtered = segments.filter(s => {
    if (filterStatus === 'Ativos' && s.status !== 'ativo') return false;
    if (filterStatus === 'Inativos' && s.status !== 'inativo') return false;
    return s.nome.toLowerCase().includes(search.toLowerCase());
  });

  const handleSave = (s: Segment) => {
    saveMutation.mutate(s);
  };

  const toggleStatus = (id: string) => {
    toggleStatusMutation.mutate(id);
  };

  const ativos = segments.filter(s => s.status === 'ativo').length;
  const inativos = segments.filter(s => s.status === 'inativo').length;

  return (
    <div className="space-y-6 font-sans">
      {modal.open && (
        <SegmentModal
          seg={modal.seg}
          organizationId={orgId}
          onClose={() => setModal({ open: false })}
          onSave={handleSave}
        />
      )}

      {/* HEADER UNIFICADO (LIGHT MODE) */}
      <div className="max-w-[1600px] mx-auto w-full px-6 pt-6 pb-2 space-y-6">
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 flex items-center gap-3">
              <Layers className="h-7 w-7 text-indigo-600" />
              Gestão de Segmentos
            </h1>
            <p className="text-slate-500 mt-1 text-sm max-w-2xl">
              Organize os segmentos de atuação da sua rede de parceiros e fornecedores.
            </p>
          </div>
          
          <div className="flex items-center gap-3 shrink-0">
            <Button 
              onClick={() => setModal({ open: true })} 
              className="bg-indigo-600 hover:bg-indigo-700 text-white h-10 px-5 font-bold shadow-md shadow-indigo-600/20"
            >
              <Plus className="h-4 w-4 mr-1.5" />
              Novo Segmento
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-sm">
            <p className="text-slate-400 text-[10px] font-bold uppercase tracking-wider mb-1">Total de Segmentos</p>
            <p className="text-2xl font-black text-slate-900">{segments.length}</p>
          </div>
          <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-sm">
            <p className="text-slate-400 text-[10px] font-bold uppercase tracking-wider mb-1">Segmentos Ativos</p>
            <p className="text-2xl font-black text-emerald-600">{ativos}</p>
          </div>
          <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-sm">
            <p className="text-slate-400 text-[10px] font-bold uppercase tracking-wider mb-1">Segmentos Inativos</p>
            <p className="text-2xl font-black text-slate-400">{inativos}</p>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-white p-3 rounded-2xl border border-slate-200 shadow-sm">
          <div className="flex bg-slate-100 p-1 rounded-xl border border-slate-200 shrink-0 w-full sm:w-auto overflow-x-auto">
            <button 
              onClick={() => setFilterStatus('Todos')}
              className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-colors whitespace-nowrap ${filterStatus === 'Todos' ? 'bg-white text-slate-900 shadow-sm border border-slate-200/50' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Todos
            </button>
            <button 
              onClick={() => setFilterStatus('Ativos')}
              className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-colors whitespace-nowrap ${filterStatus === 'Ativos' ? 'bg-white text-slate-900 shadow-sm border border-slate-200/50' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Ativos
            </button>
            <button 
              onClick={() => setFilterStatus('Inativos')}
              className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-colors whitespace-nowrap ${filterStatus === 'Inativos' ? 'bg-white text-slate-900 shadow-sm border border-slate-200/50' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Inativos
            </button>
          </div>
          <div className="relative w-full sm:max-w-xl">
            <Search className="absolute left-3.5 top-3 h-5 w-5 text-slate-400" />
            <ClearableInput 
              placeholder="Buscar segmento..." 
              value={search}
              onChange={setSearch}
              onClear={() => setSearch('')}
              className="pl-11 bg-slate-50 border-slate-200 text-slate-900 placeholder:text-slate-500 h-11 rounded-xl focus:border-indigo-500 focus:bg-white transition-colors"
            />
          </div>
        </div>
      </div>

      {/* GRID DE SEGMENTOS */}
      <div className="max-w-[1600px] mx-auto w-full px-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {filtered.map(seg => (
            <Card
              key={seg.id}
              className={`rounded-2xl border shadow-sm transition-all duration-150 ${
                seg.status === 'ativo'
                  ? 'border-slate-200 hover:border-indigo-200 hover:shadow-md'
                  : 'border-slate-100 opacity-60'
              }`}
            >
              <CardContent className="p-5">
                <div className="flex items-start justify-between gap-2 mb-3">
                  <div className="h-10 w-10 rounded-xl bg-indigo-50 flex items-center justify-center shrink-0">
                    <Layers className="h-5 w-5 text-indigo-600" />
                  </div>
                  <span className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full border ${
                    seg.status === 'ativo'
                      ? 'bg-green-50 text-green-700 border-green-200'
                      : 'bg-slate-100 text-slate-500 border-slate-200'
                  }`}>
                    {seg.status === 'ativo' ? 'Ativo' : 'Inativo'}
                  </span>
                </div>

                <h3 className="font-bold text-slate-900 text-sm mb-1">{seg.nome}</h3>
                {seg.descricao && (
                  <p className="text-xs text-slate-500 mb-3 leading-relaxed line-clamp-2">{seg.descricao}</p>
                )}

                <div className="flex items-center gap-2 text-[10px] text-slate-400 mb-4">
                  <Building2 className="h-3 w-3" />
                  <span>0 empresa(s)</span>
                </div>

                <div className="flex items-center gap-2 pt-3 border-t border-slate-100">
                  <button
                    onClick={() => setModal({ open: true, seg })}
                    className="flex-1 flex items-center justify-center gap-1 text-[10px] font-bold text-slate-600 hover:text-indigo-700 hover:bg-indigo-50 py-1.5 rounded-lg transition-colors"
                  >
                    <Edit2 className="h-3 w-3" /> Editar
                  </button>
                  <button
                    onClick={() => toggleStatus(seg.id)}
                    className={`flex-1 flex items-center justify-center gap-1 text-[10px] font-bold py-1.5 rounded-lg transition-colors ${
                      seg.status === 'ativo'
                        ? 'text-slate-500 hover:text-red-600 hover:bg-red-50'
                        : 'text-slate-500 hover:text-green-600 hover:bg-green-50'
                    }`}
                  >
                    {seg.status === 'ativo'
                      ? <><ToggleLeft className="h-3 w-3" /> Inativar</>
                      : <><ToggleRight className="h-3 w-3" /> Ativar</>
                    }
                  </button>
                </div>
              </CardContent>
            </Card>
          ))}

        </div>
      </div>
    </div>
  );
}
