-- HISTORICAL MIGRATION PLACEHOLDER
-- Version: 20260825013456
-- Remote migration already applied before local history reconciliation.
-- Original SQL unavailable in repository history.
-- DO NOT use this file as proof of clean replay.
-- Tracked under B1R-015 migration baseline debt.
